> **About this Notebook**  
> This notebook is part of the *Advanced Python* video series created in collaboration with **Irancell Academy**.  
> 🎥 Videos and full article: [الگوریتمستان - پایتون پیشرفته آکادمی ایرانسل](https://www.amasoudfam.ir/blog/%D9%88%DB%8C%D8%AF%D8%A6%D9%88-%D9%BE%D8%A7%DB%8C%D8%AA%D9%88%D9%86-%D9%BE%DB%8C%D8%B4%D8%B1%D9%81%D8%AA%D9%87-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86%D8%B3%D9%84/)

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
classes = 'col-xs-6 col-sm-6 col-md-3 col-lg-3 full_size'
url = 'https://shahrvand.ir/fa/product/cat/%D8%A2%D8%B1%D8%A7%DB%8C%D8%B4%DB%8C-%D8%A8%D9%87%D8%AF%D8%A7%D8%B4%D8%AA%DB%8C/%D8%AF%D8%B3%D8%AA%D9%85%D8%A7%D9%84-%DA%A9%D8%A7%D8%BA%D8%B0%DB%8C-%D9%88-%D8%B3%D9%84%D9%88%D9%84%D8%B2%DB%8C/250-%D8%AF%D8%B3%D8%AA%D9%85%D8%A7%D9%84-%DA%A9%D8%A7%D8%BA%D8%B0%DB%8C.html#/pagesize-1000/stock-1'
driver = webdriver.Edge()
driver.get(url)
driver.implicitly_wait(5)
content = driver.page_source
driver.quit()
soup = BeautifulSoup(content, 'html.parser')
names = []
prices = []
for section in soup.find_all('div', attrs={'class': classes}):
    names.append(section.find('a', attrs={'class': 'title'}).text)
    prices.append(section.find('div', attrs={'class': 'new_price'}).text.strip())

In [2]:
len(names)

30

In [3]:
len(prices)

30

In [4]:
import pandas as pd
df = pd.DataFrame({'title': names, 'price': prices})

In [5]:
df

                                                title          price
0                     دستمال سفره کاغذی 20 عددی پرمیس   33,127 تومان
1                    دستمال کاغذی دو لایه 100 برگ تنو   35,600 تومان
2             دستمال ماشین اسکاچ دو لایه 100 برگ چشمک   35,937 تومان
3    دستمال کاغذی مینی طرح گلبرگ دو لایه 100 برگ چشمک   35,937 تومان
4                            دستمال جیبی 6 عددی پرمیس   36,840 تومان
5                  دستمال کاغذی دو لایه 100 برگ پرمیس   37,303 تومان
6                  دستمال کاغذی دو لایه 100 برگ گل‌پر   41,805 تومان
7                     دستمال کاغذی خاتم 200 برگ پرمیس   37,942 تومان
8              دستمال کاغذی نرگس دو لایه 100 برگ چشمک   48,185 تومان
9       دستمال کاغذی بوتانیک رز دو لایه 100 برگ چشمک    48,185 تومان
10                   دستمال کاغذی دو لایه 150 برگ تنو   54,600 تومان
11                   دستمال کاغذی سه لایه 100 برگ تنو   54,600 تومان
12                 دستمال کاغذی سه لایه 100 برگ پاپیا   59,300 تومان
13                 دستمال کاغذی دو لایه 150 برگ پاپیا   59,300 تومان
14      دستمال کاغذی طرح o-Box دو لایه 150 برگ کیولین   41,510 تومان
15  دستمال کاغذی طرح کلکسیون بافت دو لایه 150 برگ ...   58,140 تومان
16                    دستمال کاغذی خاتم 300 برگ پرمیس   55,449 تومان
17            دستمال کاغذی نرگس دو لایه 150 برگ چشمک    69,572 تومان
18       دستمال کاغذی بوتانیک رز دو لایه 150 برگ چشمک   69,572 تومان
19          دستمال کاغذی بوتانیک دو لایه 150 برگ چشمک   69,572 تومان
20        دستمال کاغذی طرح قاصدک دو لایه 150 برگ چشمک   69,572 تومان
21      دستمال كاغذی نقره‌ای دو لایه 150 برگ سافتلن     73,000 تومان
22                 دستمال کاغذی سه لایه 100 یرگ نانسی   77,000 تومان
23      دستمال كاغذی سری طلایی سه لایه 100 برگ سافتلن   77,900 تومان
24                دستمال کاغذی دو لایه 250 عددی پاپیا   88,900 تومان
25                           دستمال کاغذی 4 عددی چشمک  192,739 تومان
26  دستمال کاغذی اقتصادی دو لایه 250 برگ 4 عددی راشین  330,278 تومان
27    پک دستمال کاغذی دولایه 200 برگ 10 عددی ایزی پیک  331,058 تومان
28       دستمال کاغذی دو لایه 100 برگ 10 عددی کلین آپ  317,300 تومان
29   دستمال کاغذی اقتصادی 200 برگ دولایه 8 عددی راشین  528,444 تومان

In [6]:
df.sort_values('price')

                                                title          price
25                           دستمال کاغذی 4 عددی چشمک  192,739 تومان
28       دستمال کاغذی دو لایه 100 برگ 10 عددی کلین آپ  317,300 تومان
0                     دستمال سفره کاغذی 20 عددی پرمیس   33,127 تومان
26  دستمال کاغذی اقتصادی دو لایه 250 برگ 4 عددی راشین  330,278 تومان
27    پک دستمال کاغذی دولایه 200 برگ 10 عددی ایزی پیک  331,058 تومان
1                    دستمال کاغذی دو لایه 100 برگ تنو   35,600 تومان
2             دستمال ماشین اسکاچ دو لایه 100 برگ چشمک   35,937 تومان
3    دستمال کاغذی مینی طرح گلبرگ دو لایه 100 برگ چشمک   35,937 تومان
4                            دستمال جیبی 6 عددی پرمیس   36,840 تومان
5                  دستمال کاغذی دو لایه 100 برگ پرمیس   37,303 تومان
7                     دستمال کاغذی خاتم 200 برگ پرمیس   37,942 تومان
14      دستمال کاغذی طرح o-Box دو لایه 150 برگ کیولین   41,510 تومان
6                  دستمال کاغذی دو لایه 100 برگ گل‌پر   41,805 تومان
8              دستمال کاغذی نرگس دو لایه 100 برگ چشمک   48,185 تومان
9       دستمال کاغذی بوتانیک رز دو لایه 100 برگ چشمک    48,185 تومان
29   دستمال کاغذی اقتصادی 200 برگ دولایه 8 عددی راشین  528,444 تومان
10                   دستمال کاغذی دو لایه 150 برگ تنو   54,600 تومان
11                   دستمال کاغذی سه لایه 100 برگ تنو   54,600 تومان
16                    دستمال کاغذی خاتم 300 برگ پرمیس   55,449 تومان
15  دستمال کاغذی طرح کلکسیون بافت دو لایه 150 برگ ...   58,140 تومان
12                 دستمال کاغذی سه لایه 100 برگ پاپیا   59,300 تومان
13                 دستمال کاغذی دو لایه 150 برگ پاپیا   59,300 تومان
18       دستمال کاغذی بوتانیک رز دو لایه 150 برگ چشمک   69,572 تومان
17            دستمال کاغذی نرگس دو لایه 150 برگ چشمک    69,572 تومان
19          دستمال کاغذی بوتانیک دو لایه 150 برگ چشمک   69,572 تومان
20        دستمال کاغذی طرح قاصدک دو لایه 150 برگ چشمک   69,572 تومان
21      دستمال كاغذی نقره‌ای دو لایه 150 برگ سافتلن     73,000 تومان
22                 دستمال کاغذی سه لایه 100 یرگ نانسی   77,000 تومان
23      دستمال كاغذی سری طلایی سه لایه 100 برگ سافتلن   77,900 تومان
24                دستمال کاغذی دو لایه 250 عددی پاپیا   88,900 تومان

In [7]:
import re
pattern = r'\b\d{1,3}-\d{6}-\d\b'
text = '''kjhdf sdfhsdjkhf  111-222222-3 dskfhsdiufhskf dkshf 22-22222222-3 dsjkfhskdfhskhjf skddhf 
sk 12-123456-7 dshgfjsgdfjshgf s 1234-123456-7 dsfsdkjfhskjhfsdkjfhsd dfsf 111-222222-33'''
re.findall(pattern, text)

['111-222222-3', '12-123456-7']

In [8]:
import re
pattern = r'\d{1,3}-\d{6}-\d'
text = '''kjhdf sdfhsdjkhf  111-222222-3 dskfhsdiufhskf dkshf 22-22222222-3 dsjkfhskdfhskhjf skddhf 
sk 12-123456-7 dshgfjsgdfjshgf s 1234-123456-7 dsfsdkjfhskjhfsdkjfhsd dfsf 111-222222-33'''
re.findall(pattern, text)

['111-222222-3', '12-123456-7', '234-123456-7', '111-222222-3']

In [9]:
text='63,500 تومان'
pattern = r'\d+'
re.findall(pattern, text.replace(',', ''))

['63500']

In [10]:
df['new_price'] = df['price'].apply(lambda x: int(re.findall(pattern, x.replace(',', ''))[0]))

In [11]:
df.sort_values('new_price')

,title,price,new_price
0,دستمال سفره کاغذی 20 عددی پرمیس,"33,127 تومان",33127
1,دستمال کاغذی دو لایه 100 برگ تنو,"35,600 تومان",35600
2,دستمال ماشین اسکاچ دو لایه 100 برگ چشمک,"35,937 تومان",35937
3,دستمال کاغذی مینی طرح گلبرگ دو لایه 100 برگ چشمک,"35,937 تومان",35937
4,دستمال جیبی 6 عددی پرمیس,"36,840 تومان",36840
5,دستمال کاغذی دو لایه 100 برگ پرمیس,"37,303 تومان",37303
7,دستمال کاغذی خاتم 200 برگ پرمیس,"37,942 تومان",37942
14,دستمال کاغذی طرح o-Box دو لایه 150 برگ کیولین,"41,510 تومان",41510
6,دستمال کاغذی دو لایه 100 برگ گل‌پر,"41,805 تومان",41805
8,دستمال کاغذی نرگس دو لایه 100 برگ چشمک,"48,185 تومان",48185
9,دستمال کاغذی بوتانیک رز دو لایه 100 برگ چشمک,"48,185 تومان",48185
10,دستمال کاغذی دو لایه 150 برگ تنو,"54,600 تومان",54600
11,دستمال کاغذی سه لایه 100 برگ تنو,"54,600 تومان",54600
16,دستمال کاغذی خاتم 300 برگ پرمیس,"55,449 تومان",55449
15,دستمال کاغذی طرح کلکسیون بافت دو لایه 150 برگ ...,"58,140 تومان",58140
12,دستمال کاغذی سه لایه 100 برگ پاپیا,"59,300 تومان",59300
13,دستمال کاغذی دو لایه 150 برگ پاپیا,"59,300 تومان",59300
20,دستمال کاغذی طرح قاصدک دو لایه 150 برگ چشمک,"69,572 تومان",69572
19,دستمال کاغذی بوتانیک دو لایه 150 برگ چشمک,"69,572 تومان",69572
18,دستمال کاغذی بوتانیک رز دو لایه 150 برگ چشمک,"69,572 تومان",69572
17,دستمال کاغذی نرگس دو لایه 150 برگ چشمک,"69,572 تومان",69572
21,دستمال كاغذی نقره‌ای دو لایه 150 برگ سافتلن,"73,000 تومان",73000
22,دستمال کاغذی سه لایه 100 یرگ نانسی,"77,000 تومان",77000
23,دستمال كاغذی سری طلایی سه لایه 100 برگ سافتلن,"77,900 تومان",77900
24,دستمال کاغذی دو لایه 250 عددی پاپیا,"88,900 تومان",88900
25,دستمال کاغذی 4 عددی چشمک,"192,739 تومان",192739
28,دستمال کاغذی دو لایه 100 برگ 10 عددی کلین آپ,"317,300 تومان",317300
26,دستمال کاغذی اقتصادی دو لایه 250 برگ 4 عددی راشین,"330,278 تومان",330278
27,پک دستمال کاغذی دولایه 200 برگ 10 عددی ایزی پیک,"331,058 تومان",331058
29,دستمال کاغذی اقتصادی 200 برگ دولایه 8 عددی راشین,"528,444 تومان",528444

In [12]:
re.match(r'\d{1,3}-\d{6}-\d', '111-222222-3')

In [13]:
re.sub?

Signature: re.sub(pattern, repl, string, count=0, flags=0)
Docstring:
Return the string obtained by replacing the leftmost
non-overlapping occurrences of the pattern in string by the
replacement repl.  repl can be either a string or a callable;
if a string, backslash escapes in it are processed.  If it is
a callable, it's passed the Match object and must return
a replacement string to be used.
File:      c:\program files\python311\lib\re\__init__.py
Type:      function

In [14]:
import re
pattern = r'\b\d{1,3}-\d{6}-\d\b'
text = '''kjhdf sdfhsdjkhf  111-222222-3 dskfhsdiufhskf dkshf 22-22222222-3 dsjkfhskdfhskhjf skddhf 
sk 12-123456-7 dshgfjsgdfjshgf s 1234-123456-7 dsfsdkjfhskjhfsdkjfhsd dfsf 111-222222-33'''
re.sub(pattern, '***', text)

'kjhdf sdfhsdjkhf  *** dskfhsdiufhskf dkshf 22-22222222-3 dsjkfhskdfhskhjf skddhf \nsk *** dshgfjsgdfjshgf s 1234-123456-7 dsfsdkjfhskjhfsdkjfhsd dfsf 111-222222-33'